### ISSUE TITLE
Rework of Examples Section

### ISSUE THREAD

**Issue by SnowMB** [nextcloud/docker#103]
This is a little to do list to improve the examples section:

- [ ] split the examples into subfolders
- [ ] docker-compose example:
  - [ ] use JrCs proxy companion #98 
  - [ ] Use volumes instead of mounted folders 
  - [ ] add proxy settings for upload size #95
  - [ ] don't use an external network as it is not needed when the proxy is defined in the same file. Use multiple networks in the file instead
  - [ ] add example for apache version
  - [ ] change mounts to only `/var/www/html` since it's simpler and less error-prone (would prevent that "config directory not writeable"-error #75 #86) 
  - [ ] remove container names (not needed)
  - [ ] remove `${DOMAIN}`, it isn't explained anywhere
  - [ ] rework the `README.md` to explain the example in detail
  - [x] in fpm version the fpm addition to the tag is missing `nextcloud:fpm` (fixed in #112)
  - [ ] Add example with "indiehosters"-style 2nd container running a cron job #123 
  - [ ] Don't use `volumes_from` in the fpm example since it isn't supported in docker-compose file version 3 
- [ ] derived Dockerfiles:
  - [ ] Add examples for both cases apache and fpm
  - [ ] Add example for preview generation dependencies #63  
  - [ ] Add examples for manipulating the sources #91 #104

**Comment by MatthewVance** [comment]
It would also be better if all the networks were not `proxy-tier`. A more secure network architecture would separate the database into a separate network tier than the frontend proxy. The app tier would be in both tiers to bridge the two. See https://docs.docker.com/compose/networking/#specifying-custom-networks for an example.

It might be easier and cleaner if the example reveres proxy server was [Caddy](https://caddyserver.com/) since it natively supports [automatic https](https://caddyserver.com/docs/automatic-https).

**Comment by SnowMB** [comment]
@MatthewVance That is what I intend to do. In fact It would look like this:

proxy tier:
 - proxy
 - letsencrypt
 - nextcloud
 - (collabora)

default network:
 - nextcloud
 - database
 - (redis)
 - (cron)

Of course there could be additional networks for redis and cron, but for the sake of simplicity I think it's unnecessary.

**Comment by MatthewVance** [comment]
Thanks Marc. That sounds good. I agree it doesn't make sense to add additional networks for redis and cron.

**Comment by LorbusChris** [comment]
It would also be very nice to have an example of how to build nextcloud apps like the mail app into the image, so they're directly installedupon startup.

**Comment by robclay** [comment]
Could you also add an example page for command line startups (Not composer) for those (and me) that do not have access to composer?  i.e. qnap box.
